POST http://localhost:4000/api/users
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "Test@1234",
  "sex": "male",
  "age": 30
}

###
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "username": "testusers",
  "email": "testusers@example.com",
  "password": "Test*1234",
  "sex": "male",
  "age": 1
}

###
GET http://localhost:4000/api/users/count